import Head from "next/head";
import Image from "next/image";
import ContentComponent from "../components/content";
import FeatureComponent from "../components/feature";
import FooterComponent from "../components/footer";
import HeroComponent from "../components/hero";
import SubscribeComponent from "../components/subscribe";
import styles from "../styles/Home.module.css";
import PocketBase, { BaseAuthStore } from "pocketbase";
import SwiperComponent from "../components/swiper";
import { createContext, useEffect } from "react";
import { InferGetServerSidePropsType } from "next";

interface IContextSite {
  value : InferGetServerSidePropsType<typeof getServerSideProps>
}
class NextAuthStore extends BaseAuthStore {
  constructor(req, res) {
    super();
    //@ts-ignore
    this.req = req;
    //@ts-ignore
    this.res = res;
    //@ts-ignore
    this.loadFromCookie(this.req?.headers?.cookie);
  }

  save(token, model) {
    super.save(token, model);
    //@ts-ignore
    this.res?.setHeader("set-cookie", this.exportToCookie());
  }

  clear() {
    super.clear();
    //@ts-ignore
    this.res?.setHeader("set-cookie", this.exportToCookie());
  }
}

export async function getServerSideProps({ req, res }) {
  const client = new PocketBase("http://127.0.0.1:8090");
  const adminData = await client.admins.authViaEmail('farisraihanhadibrata@gmail.com', 'farisraihanhadibrata@gmail.com');
  const userData = await client.users.authViaEmail('farisraihanhadibrata@gmail.com', 'farisraihanhadibrata@gmail.com');
  // client.authStore.save(userData.token, userData.user)
  client.authStore =  await new NextAuthStore(req, res);
  await client.authStore.save(adminData.token, adminData.admin)
  const siteName = await client.records.getOne("site", "959zd64b8lpc70j").then(i => i.export());
  const menuList = await client.collections.getOne("menuList")
  return {
    props: {
      siteName,
      menuList,
    },
  };
}

export const SiteContext : any  = createContext({});
export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteContext.Provider value={props}>
        <HeroComponent />
        <SwiperComponent />
        <ContentComponent />
        <FeatureComponent />
        <SubscribeComponent />
        <FooterComponent />
      </SiteContext.Provider>
    </>
  );
}
